### ISSUE TITLE
Version '1:0.4.4-0ubuntu1~trusty' for 'solc' was not found

### ISSUE THREAD

**Issue by plur9** [ConsenSys/MultiSigWallet#56]
When running "vagrant up" I get the above error. From what I see the 0.4.4 build is not available anymore. Can we use later versions?

**Comment by giacomolicari** [comment]
Thanks for your report @plur9. Updates soon.

**Comment by giacomolicari** [comment]
Hi @plur9, try it again with master branch, it should work now.

**Comment by plur9** [comment]
Yes, the installation works now. But the tests fail as the solidity compiler is later version that the one in requested in sol files:

CompileError: <stdin>:1:1: Error: Source file requires different compiler version (current compiler is 0.4.10+commit.59099908.Linux.g++ - note that nightly builds are considered to be strictly less than the released version pragma solidity 0.4.4; 

before posting here, I also removed the version number for solc, got a same error but didn't want to change .sol files as I don't know solidity and what the changes are.

Also, this is unrelated to the above problem. If I try just to deploy the MultiSig, I get this error:

vagrant@vagrant-ubuntu-trusty-64:/vagrant/contracts$ python deploy.py -f deploy/MultiSig.json
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
Traceback (most recent call last):
  File "deploy.py", line 204, in <module>
    setup()
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "deploy.py", line 200, in setup
    deploy = Deploy(protocol, host, port, add_dev_code, verify_code, contract_dir, gas, gas_price, private_key)
  File "deploy.py", line 27, in __init__
    self.user_address = self.json_rpc.eth_coinbase()["result"]
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethjsonrpc/ethjsonrpc.py", line 117, in eth_coinbase
    return self._call('eth_coinbase')
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethjsonrpc/ethjsonrpc.py", line 22, in _call
    response = requests.post("{}://{}:{}".format(self.protocol, self.host, self.port), data=data, headers=headers).json()
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

Any ideas before I go into troubleshooting myself?

Tnx.
