### ISSUE TITLE
Following your tutorial produces the following when running: python -m unittest tests.test_multisig_wallet

### ISSUE THREAD

**Issue by RFVenter** [ConsenSys/MultiSigWallet#66]
vagrant@vagrant-ubuntu-trusty-64:/vagrant/contracts$ python -m unittest tests.te                                             st_multisig_wallet
/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum/_solidi                                             ty.py:353: UserWarning: solc_wrapper is deprecated, please use the functions com                                             pile_file or compile_code
  warnings.warn('solc_wrapper is deprecated, please use the functions compile_fi                                             le or compile_code')
E
======================================================================
ERROR: test (tests.test_multisig_wallet.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_multisig_wallet.py", line 39, in test
    constructor_parameters=constructor_parameters)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/unittest/case.py", lin                                             e 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum                                             /tester.py", line 215, in abi_contract
    contract_interface = compiler.mk_full_signature(sourcecode, path=path, **kwa                                             rgs)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum                                             /_solidity.py", line 384, in mk_full_signature
    result = cls._code_or_path(code, path, contract_name, libraries, 'abi', extr                                             a_args)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum                                             /_solidity.py", line 371, in _code_or_path
    result = compile_code(sourcecode, libraries=libraries, combined=combined, ex                                             tra_args=extra_args)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum                                             /_solidity.py", line 339, in compile_code
    raise CompileError(stderrdata)
CompileError: Warning: This is a pre-release compiler version, please do not use                                              it in production.
<stdin>:1:1: Error: Source file requires different compiler version (current com                                             piler is 0.4.11-develop.2017.5.3+commit.00933b99.Linux.g++ - note that nightly b                                             uilds are considered to be strictly less than the released version
pragma solidity 0.4.4;
^--------------------^

**Comment by hitchcott** [comment]
I fixed this by changing pragma in the contracts to `pragma solidity ^0.4.4;`

But now I'm running into a different error:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/contracts$ python -m unittest tests.test_multisig_wallet
/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum/_solidity.py:353: UserWarning: solc_wrapper is deprecated, please use the functions compile_file or compile_code
  warnings.warn('solc_wrapper is deprecated, please use the functions compile_file or compile_code')
E
======================================================================
ERROR: test (tests.test_multisig_wallet.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_multisig_wallet.py", line 44, in test
    gas = self.s.block.gas_used
AttributeError: FakeBlock instance has no attribute 'gas_used'

----------------------------------------------------------------------
Ran 1 test in 0.795s

FAILED (errors=1)
vagrant@vagrant-ubuntu-trusty-64:/vagrant/contracts$
```

**Comment by iam-peekay** [comment]
@RFVenter @Georgi87 I had to comment out the assertions that were using `block.gas_used` and `block.get_balance` because it kept saying the `FakeBlock` instance doesn't have both of those attributes. 

https://github.com/ethereum/pyethereum/blob/8edc5954fb8b6697cb7c9d7d85ed71e5f6d74e0f/ethereum/snapshot.py

I'm happy to make a PR to update the tests accordingly, but wanted to confirm I'm not missing something? @Georgi87
